### PR TITLE
Settings view updates

### PR DESCRIPTION
**Pull request by jamie-conlon**
- Added new view controller for sync settings. 
- Updated the settings screen.

Code is still a bit messy in places so will need tidying up.
Doing a pull request to see if you guys think it works and I should continue with it.

### CODE REVIEW

**Comment by mgmart** [comment]
I think this pull request matches exactly the work we currently do. I would like to have a nicer settings view in the current release. I will not be able to test the pr until the second week of January.

I would suggest that further clean up of the code should be delayed after we have a outcome of the discussion wether to use Storyboards and/or Swift in the future.

**Comment by webframp** [comment]
Thanks for the contribution! I'll take some time this evening to test it out.

**Comment by mgmart** [comment]
I love the new look of the settings screen. Definitely an improvement. 🦄

**Comment by webframp** [comment]
Agreed, @jamie-conlon you mentioned some cleanup you wanted to do. Feel free to just do a new pr for that if you want.

**Comment by jamie-conlon** [comment]
@webframp Over the past few days I've rewritten the view controllers in Swift and used a storyboard. It's more of an extreme cleanup! I thought it might be worth a try because I'd imagine the settings views won't be too different in v2. 
I'll submit a PR in the next day or two.

**Comment by webframp** [comment]
Sounds great @jamie-conlon, I'll watch for it!

**Pull request merged**
