### PR TITLE
all warnings are removed

### PR DESCRIPTION
**Pull request by mgmart**
Major code changes were necessary!

### CODE REVIEW

**Comment by mgmart** [comment]
Due to unmerged PRs testing of this PR is nearly impossible. Best approach seems to be to handle this PR separately.

**Comment by webframp** [comment]
Agree on waiting for this one to go through testflight, will work on getting 1.7.3 out

**Comment by webframp** [comment]
Next up: this one. @mgmart any reasons to wait on this before merging?

**Comment by mgmart** [comment]
Not at all. Please keep in mind to do a `pod update` before building.

**Comment by webframp** [comment]
Cool, I figured that might be needed due to 66cee5f23934ab09994ebd2a665971962121743f

**Comment by mgmart** [comment]
The real breaker is ff250bd 😉

**Pull request merged**
