### PR TITLE
Starting a test file with everything

### PR DESCRIPTION
**Pull request by webframp**
This test file could be used to exercise the rendering and is starting to get little bit of everything, but what's it missing?

No actual tests using this, just brainstorming for #141

### CODE REVIEW

**Comment by webframp** [comment]
It would make sense to have at least one sample of each of supported markup element: http://orgmode.org/manual/Markup.html 

@mgmart thoughts?

**Comment by mgmart** [comment]
> It would make sense to have at least one sample of each of supported markup element:

definitely.

> Should be shared with developers, testers and users

What about collecting the test-files in MobileOrg/mobileorg.github.io?
I assume that we shall not use test-files in 1.7. But we could use them in the case we need to reproduce a reported defect like #97.

Test-files would be then available from the website for everyone to use. 

We should make it mandatory for 2.0 to use the files in unit-tests.

**Comment by webframp** [comment]
That's fine with me

**Comment by mgmart** [comment]
Should we make a doc folder in the main repo? Keeping the website there?  If we're keeping MobileOrg/mobileorg.github.io, it would be kind if you could commit the test-file there after updating to new appearance.

**Comment by webframp** [comment]
Closing, added this file over in MobileOrg/mobileorg.github.io@2bbf2e21a226aab129c8da8469568e3d0d85f052

**Pull request closed without merging**
