### PR TITLE
Enhancement/ios11 no swift migration

### PR DESCRIPTION
**Pull request by mgmart**
Builds successfully with Xcode 9. Tests run fine also. Should be tested thoroughly, though. 

Proper user tests are necessary also because of the code changes already made by the last PR.

### CODE REVIEW

**Comment by webframp** [comment]
Looks good, I could try and get this out to testflight this week.

**Comment by DivineDominion** [comment]
Any progress on this?

**Comment by mgmart** [comment]
@webframp, if you push this to TestFlight please keep #162 in mind.

**Comment by webframp** [comment]
Thanks @mgmart I had forgot about that

**Comment by mgmart** [comment]
@webframp, we would need this out and tested before we could work on bug-fixes like #220. Don't know how @DivineDominion managed to create #219. I'm not able to work on `develop` with Xcode 9 and iOS 11 as target.

**Comment by DivineDominion** [comment]
Can I help somehow? I don't understand what problems you run into @mgmart. Can't you build the target at all?

**Comment by webframp** [comment]
Thanks for your persistence @mgmart it's essential help. I'll work on getting this released for test. New machine, new setup, rebuilding me environment is slower than I expected.

**Comment by webframp** [comment]
Thanks for your persistence @mgmart it's essential help. I'll work on getting this released for test. New machine, new setup, rebuilding me environment is slower than I expected.

**Comment by webframp** [comment]
Long overdue, finally merged. Thanks @mgmart for the code and the patience!

**Pull request merged**
