### PR TITLE
removed readableContentGuide

### LINKED ISSUE #150: Right Side Whitespace on iPAd
On iPad the right side of Outline view is misaligned.
There is more whitespace in landscape mode. 
The bigger the screen the more visible the effect is.

### LINKED ISSUE #151: Capture List has whitespace left and right
Same effect as outline (#150). Difference is that content is centred.

### PR DESCRIPTION
**Pull request by mgmart**
Fixes #150
Fixes #151

http://stackoverflow.com/a/33410884

### CODE REVIEW

**Comment by mgmart** [comment]
fix for #153 added

**Comment by webframp** [comment]
simulator screen shot jan 24 2017 9 48 33 am

Still a little padding on the left hand side for me, do you get the same?
Right hand side goes to the edge of the screen.

**Comment by mgmart** [comment]
It's the same on iPhone since we've compiled it with Xcode 8.
Will try to remove the indentation of separator later. Look ugly even on iPhone.

**Comment by mgmart** [comment]
Last commit is not tested with tags and priorities.

**Pull request merged**
