### PR TITLE
Base iCloud support

### LINKED ISSUE #201: Feature request: iCloud drive support
From Kirill Simagin in the App Store Reviews.

Not sure if it's worth effort in the v1.7 series or if it's better to focus in v2

### PR DESCRIPTION
**Pull request by dive**
Hello there,

This is a base implementation of iCloud support. It works in the same way as WebDAV and Dropbox synchronisation options.

## Good to know
- CloudKit service support disabled in the entitlements, we do not need it to be able to sync files via iCloud;
- The implementation assumes that the application has only one iCloud Container defined;
- iCloud container described in the `MobileOrg-Info-*.plist` files (note, I am using the same container for all versions - AdHoc, Debug, Release. It is easier to debug and access data; and I did not find any good reasons to split them);
- Check `NSUbiquitousContainers` definition within `plist` files, and you will notice that the name of the container is the same as the container name on the "Signing & Capabilities" tab in the Xcode project settings - `iCloud.com.mobileorg.mobileorg`;
- You have to **uninstall the currently installed version** of the application (on the simulator or the real device) and then install the one with iCloud support to make it work (this is not the case for official releases via AppStore or TestFlight, only for Debug or any installations directly from Xcode). Otherwise, iOS will not register the fact that the application can access iCloud storage;
- By default, "MobileOrg" folder with the application icon will appear in your iCloud storage after the first sync from the application itself. All `.org` files will be stored inside.

## Technical details

- All file operations are asynchronius;
- I use a lot of `fatalError` for controversial scenarios to be able to collect crashes with proper stack-traces. I think this is fine for the `develop` branch. Maybe, if there will be a release version, we can replace them with something less destructive;
- Unit-tests are included.

## Synchronisation with Emacs

To set up synchronisation with Emacs you have to change `org-mobile-directory` in your `init.el` file to something like this:
```
(setq org-mobile-directory "~/Library/Mobile Documents/iCloud~com~mobileorg~mobileorg/Documents")
```
You can verify the path by opening iCloud Drive folder in the Finder, look for MobileOrg folder inside, right-click on it, hold Alt and select "Copy "MobileOrg" as Pathname". The proper path will be copied to the clipboard.

**NOTE:** The folder will appear in your iCloud Drive only after the initial sync initiated from the mobile application.

## For a reviewer/maintainer

For testing, I used my own containers within my development account. So, it is better to double-check that everything works as expected by whoever has access to the iTunes Connect account you use to distribute TestFlight and release builds.

Resolves #201, corresponding feature request in the tracker.

##

Let me know if you want to make any changes in the pull-request or have questions.

Cheers,
Artem

### CODE REVIEW

**Comment by webframp** [comment]
Looking great @dive thanks! I only did some cursory testing with it, but will work on getting a Testflight beta out after this is merged. 

I’m not a fan of the multiple plist approach, that’s just legacy stuff I believe.

**Comment by dive** [comment]
> Looking great @dive thanks! I only did some cursory testing with it, but will work on getting a Testflight beta out after this is merged.

Thanks. 

> I’m not a fan of the multiple plist approach, that’s just legacy stuff I believe.

Yeah, me either. Btw, it would be nice to get rid of CocoaPods and switch to Carthage. It will allow switching to a proper configuration based on `xcconfig` files. But let's try to prepare the next release of MobileOrg first. I am working on the UI rework, and then will try to resolve issues within v1.7.5 milestone.

**Comment by webframp** [comment]
> it would be nice to get rid of CocoaPods and switch to Carthage. 

I'd like to look at this post-v1.7.5 maybe, especially if it makes the development process simpler for new contributors.

**Comment by webframp** [comment]
Seems to "just work" for me so far with local testing, going to go ahead and merge into dev branch.

**Pull request merged**
