### PR TITLE
pull changes from PR into dev

### PR DESCRIPTION
**Pull request by webframp**
pulling in change from a recent PR

### CODE REVIEW

**Comment by shaiguitar** [comment]
Hey @webframp Sorry this isn't the right place to put this but just wanted to get your attention. I want to help contribute to this project but I can't seem to get it to run in xcode due to needing some certificate: 

http://shairosenfeld.com/uploads/mobile-contrib.png

https://gist.githubusercontent.com/shaiguitar/8485b70e81880ef751d0/raw/a60c78175f81a8e9d4046c41a540b41f43b61b3b/gistfile1.txt

Is there some kind of FAQ on how to set up local dev or get the APP_KEY/APP_SECRET keys?

**Comment by vermiculus** [comment]
@shaiguitar just make a normal issue.

**Comment by shaiguitar** [comment]
@vermiculus Sorry about that. Here's a dedicated issue: https://github.com/MobileOrg/mobileorg/issues/75

**Comment by webframp** [comment]
This is quite outdated now and new changes have been merged to develop branch.

**Pull request closed without merging**
