### PR TITLE
Icons update

### PR DESCRIPTION
**Pull request by d12frosted**
I have just started to work on updating icons. Sharing what I already have. I might decrease size of the unicorn (so it fits better). And I will try to consult with one of my fellow designers about the background gradient colour.

Also I am sharing [iTunesArtwork](https://dl.dropboxusercontent.com/u/14438695/MobileOrg/iTunesArtwork.zip). 

This PR misses beta and debug version of icons. Not sure how to implement it yet, so will look for solution. 

P. S. I removed old icons. It seems to be working for me without this assets, but if I misses something, just let me know.

### CODE REVIEW

**Comment by mgmart** [comment]
> This PR misses beta and debug version of icons. Not sure how to implement it yet, so will look for solution.

There are placeholders already in the Images asset catalog.

**Comment by webframp** [comment]
Since there are placeholders I'm happy to merge this without Debug and Beta icons, @d12frosted any other reason to wait on this in your opinion? Looks good to me

**Comment by d12frosted** [comment]
> There are placeholders already in the Images asset catalog.

@mgmart oh indeed 😸 

> @d12frosted any other reason to wait on this in your opinion? Looks good to me

@webframp no other reasons 😸 I'll provide other icons ASAP (just want to ask opinion of my friend first as I am no designer).

**Comment by d12frosted** [comment]
I have an update, will share it tomorrow.

**Comment by d12frosted** [comment]
I have tuned this icon so unicorn fits much better into rounded square. And also tried with yellowish colour to have a better focus on unicorn. So here are two versions. I wonder which one you prefer.

itunesartwork 2x

itunesartwork 2x

The second one is a little bit unusual. But for some reason I like it 😸 My friend hadn't time to really help me, but it's his idea to use more yellowish colour as a background.

**Comment by mgmart** [comment]
The second one, please 🦄

**Comment by d12frosted** [comment]
It looks nice on my device 😸

**Comment by webframp** [comment]
second one is good for me, makes a nice break from the old icon too. We can save actually changing the unicorn for v2

**Comment by mgmart** [comment]
SCNR!
http://orig04.deviantart.net/91c0/f/2016/191/3/4/pretty_unicorn_by_m_u_h_a-da9hfgg.png

**Comment by d12frosted** [comment]
I have updated icons (with the yellowish variant). Also I have added debug and beta versions. 

Attachments:

- [iTunesArtwork.zip](https://github.com/MobileOrg/mobileorg/files/706528/iTunesArtwork.zip) containing 512 and 1024 variants for regular, beta and debug icons. 

P. S. For some reason I see strange artefacts around the icon on my phone. Gonna investigate that.

**Comment by d12frosted** [comment]
Ok, that's something funky with my masks in `Sketch.app`. Using icons without round corners works perfectly.

**Comment by d12frosted** [comment]
Ok, uploading without any round corners. Thanks @mgmart for the link to [this forum](https://www.quora.com/Do-I-include-in-the-rounded-corners-in-my-iPhone-app-icon-design).

Attachments:

- [iTunesArtwork.zip](https://github.com/MobileOrg/mobileorg/files/706546/iTunesArtwork.zip)

P. S. Sorry for the spam.

**Comment by webframp** [comment]
Nice, looking great. @d12frosted. Ready for me to merge this?

**Pull request merged**
